package storage

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/smithy-go"
)

// sampleListVersionsXML is the real gateway response shape, generated by
// marshalling handlers.ListVersionsResult from tigris-os. Soft-delete tombstones
// arrive as Version elements carrying SoftDeleted, never as DeleteMarker
// elements, because the S3 DeleteMarker schema cannot carry Size or ETag. The
// live version and the real delete marker below must both be filtered out.
const sampleListVersionsXML = `<?xml version="1.0" encoding="UTF-8"?>
<ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>my-bucket</Name>
  <Prefix>reports/</Prefix>
  <KeyMarker>start</KeyMarker>
  <VersionIdMarker></VersionIdMarker>
  <NextKeyMarker>next-key</NextKeyMarker>
  <NextVersionIdMarker>next-version</NextVersionIdMarker>
  <MaxKeys>100</MaxKeys>
  <IsTruncated>true</IsTruncated>
  <Version>
    <Key>reports/q1.pdf</Key>
    <VersionId>1775929768707198086</VersionId>
    <IsLatest>true</IsLatest>
    <ETag>&#34;abc123&#34;</ETag>
    <Size>2048</Size>
    <Owner>
      <ID></ID>
    </Owner>
    <StorageClass>STANDARD</StorageClass>
    <SoftDeleted>true</SoftDeleted>
    <LastModified>2026-05-01T12:30:00Z</LastModified>
  </Version>
  <Version>
    <Key>reports/q2.pdf</Key>
    <VersionId>1775929768707198087</VersionId>
    <IsLatest>true</IsLatest>
    <ETag>&#34;def456&#34;</ETag>
    <Size>4096</Size>
    <Owner>
      <ID></ID>
    </Owner>
    <StorageClass>STANDARD</StorageClass>
    <SoftDeleted>true</SoftDeleted>
    <LastModified>2026-05-02T08:15:00Z</LastModified>
  </Version>
  <Version>
    <Key>reports/live.pdf</Key>
    <VersionId>1775929768707199999</VersionId>
    <IsLatest>true</IsLatest>
    <ETag>&#34;live99&#34;</ETag>
    <Size>8192</Size>
    <Owner>
      <ID></ID>
    </Owner>
    <StorageClass>STANDARD</StorageClass>
    <LastModified>2026-05-02T08:15:00Z</LastModified>
  </Version>
  <DeleteMarker>
    <Key>reports/marker.pdf</Key>
    <VersionId>1775929768707198088</VersionId>
    <IsLatest>true</IsLatest>
    <Owner>
      <ID></ID>
    </Owner>
    <LastModified>2026-05-02T08:15:00Z</LastModified>
  </DeleteMarker>
</ListVersionsResult>`

func TestListSoftDeletedObjects_RequestAndParse(t *testing.T) {
	var req *http.Request
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req = r
		_, _ = w.Write([]byte(sampleListVersionsXML))
	}))
	defer server.Close()

	cli, err := New(context.Background(),
		WithEndpoint(server.URL),
		WithAccessKeypair("test-key", "test-secret"),
		WithPathStyle(true),
	)
	if err != nil {
		t.Fatal(err)
	}

	out, err := cli.ListSoftDeletedObjects(context.Background(), &ListSoftDeletedObjectsInput{
		Bucket:    "my-bucket",
		Prefix:    "reports/",
		KeyMarker: "start",
		MaxKeys:   100,
	})
	if err != nil {
		t.Fatal(err)
	}

	if req.Method != http.MethodGet {
		t.Errorf("method = %q, want GET", req.Method)
	}
	if req.URL.Path != "/my-bucket" {
		t.Errorf("path = %q, want /my-bucket", req.URL.Path)
	}
	if !req.URL.Query().Has("versions") {
		t.Error("missing ?versions query parameter")
	}
	if got := req.URL.Query().Get("prefix"); got != "reports/" {
		t.Errorf("prefix = %q, want reports/", got)
	}
	if got := req.URL.Query().Get("key-marker"); got != "start" {
		t.Errorf("key-marker = %q, want start", got)
	}
	if got := req.URL.Query().Get("max-keys"); got != "100" {
		t.Errorf("max-keys = %q, want 100", got)
	}
	if got := req.Header.Get("X-Tigris-Soft-Delete"); got != "true" {
		t.Errorf("X-Tigris-Soft-Delete = %q, want true", got)
	}
	if req.Header.Get("Authorization") == "" {
		t.Error("missing Authorization header (SigV4)")
	}

	if len(out.Objects) != 2 {
		t.Fatalf("got %d objects, want 2", len(out.Objects))
	}
	// The live version and the real delete marker in the fixture are not
	// soft-deleted, so neither belongs in the output.
	for _, obj := range out.Objects {
		if obj.Key == "reports/live.pdf" {
			t.Error("live version must not be reported as soft-deleted")
		}
		if obj.Key == "reports/marker.pdf" {
			t.Error("real delete marker must not be reported as soft-deleted")
		}
		if !obj.SoftDeleted {
			t.Errorf("object %q has SoftDeleted = false", obj.Key)
		}
	}
	if !out.IsTruncated || out.NextKeyMarker != "next-key" || out.NextVersionIDMarker != "next-version" {
		t.Errorf("pagination fields = %+v", out)
	}
	first := out.Objects[0]
	if first.Key != "reports/q1.pdf" || first.VersionID != "1775929768707198086" {
		t.Errorf("first object key/version = %q/%q", first.Key, first.VersionID)
	}
	if first.Size != 2048 || first.ETag != `"abc123"` || !first.SoftDeleted {
		t.Errorf("first object size/etag/softdeleted = %d/%q/%v", first.Size, first.ETag, first.SoftDeleted)
	}
	want := time.Date(2026, 5, 1, 12, 30, 0, 0, time.UTC)
	if !first.LastModified.Equal(want) {
		t.Errorf("first object LastModified = %v, want %v", first.LastModified, want)
	}
}

func TestListSoftDeletedObjects_Validation(t *testing.T) {
	cli := &Client{}
	if _, err := cli.ListSoftDeletedObjects(context.Background(), &ListSoftDeletedObjectsInput{}); !errors.Is(err, ErrMissingBucket) {
		t.Fatalf("err = %v, want ErrMissingBucket", err)
	}
	if _, err := cli.ListSoftDeletedObjects(context.Background(), nil); !errors.Is(err, ErrMissingBucket) {
		t.Fatalf("nil input err = %v, want ErrMissingBucket", err)
	}
}

// sampleListBucketsXML is the real gateway response shape, generated by
// marshalling handlers.ListAllMyBucketsResult from tigris-os. Note that
// ContinuationToken is the only pagination field: there is no IsTruncated and no
// NextContinuationToken element.
const sampleListBucketsXML = `<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult>
  <Owner>
    <ID>tid_test</ID>
    <DisplayName>tid_test</DisplayName>
  </Owner>
  <Buckets>
    <Bucket>
      <Name>deleted-bucket-one</Name>
      <InitialCreatedDate>2026-06-01T10:00:00Z</InitialCreatedDate>
      <SoftDeleteInfo>
        <Enabled>true</Enabled>
        <RetentionDays>7</RetentionDays>
      </SoftDeleteInfo>
      <CreationDate>2026-06-01T10:00:00Z</CreationDate>
    </Bucket>
    <Bucket>
      <Name>deleted-bucket-two</Name>
      <InitialCreatedDate>2026-05-15T08:30:00Z</InitialCreatedDate>
      <SoftDeleteInfo>
        <Enabled>true</Enabled>
        <RetentionDays>30</RetentionDays>
      </SoftDeleteInfo>
      <CreationDate>2026-05-20T09:00:00Z</CreationDate>
    </Bucket>
  </Buckets>
  <ContinuationToken>next-token</ContinuationToken>
</ListAllMyBucketsResult>`

func TestListSoftDeletedBuckets_RequestAndParse(t *testing.T) {
	var req *http.Request
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req = r
		_, _ = w.Write([]byte(sampleListBucketsXML))
	}))
	defer server.Close()

	cli, err := New(context.Background(),
		WithEndpoint(server.URL),
		WithAccessKeypair("test-key", "test-secret"),
		WithPathStyle(true),
	)
	if err != nil {
		t.Fatal(err)
	}

	out, err := cli.ListSoftDeletedBuckets(context.Background(), &ListSoftDeletedBucketsInput{
		ContinuationToken: "start-token",
		MaxBuckets:        50,
	})
	if err != nil {
		t.Fatal(err)
	}

	if req.Method != http.MethodGet {
		t.Errorf("method = %q, want GET", req.Method)
	}
	if req.URL.Path != "/" {
		t.Errorf("path = %q, want /", req.URL.Path)
	}
	if got := req.URL.Query().Get("OnlyDeleted"); got != "true" {
		t.Errorf("OnlyDeleted = %q, want true", got)
	}
	// The pagination parameters are the standard S3 kebab-case names. The server
	// reads them case-sensitively, so PascalCase variants are silently ignored.
	if got := req.URL.Query().Get("continuation-token"); got != "start-token" {
		t.Errorf("continuation-token = %q, want start-token", got)
	}
	if got := req.URL.Query().Get("max-buckets"); got != "50" {
		t.Errorf("max-buckets = %q, want 50", got)
	}
	if req.URL.Query().Has("ContinuationToken") || req.URL.Query().Has("MaxBuckets") {
		t.Error("PascalCase pagination parameters are ignored by the server")
	}
	if req.Header.Get("Authorization") == "" {
		t.Error("missing Authorization header (SigV4)")
	}

	if len(out.Buckets) != 2 {
		t.Fatalf("got %d buckets, want 2", len(out.Buckets))
	}
	if !out.IsTruncated || out.NextContinuationToken != "next-token" {
		t.Errorf("pagination fields = %+v", out)
	}
	first := out.Buckets[0]
	if first.Name != "deleted-bucket-one" {
		t.Errorf("first bucket name = %q, want deleted-bucket-one", first.Name)
	}
	if first.RetentionDays != 7 {
		t.Errorf("first bucket retention days = %d, want 7", first.RetentionDays)
	}
	wantCreated := time.Date(2026, 6, 1, 10, 0, 0, 0, time.UTC)
	if !first.CreationDate.Equal(wantCreated) {
		t.Errorf("first bucket CreationDate = %v, want %v", first.CreationDate, wantCreated)
	}
	second := out.Buckets[1]
	if second.Name != "deleted-bucket-two" || second.RetentionDays != 30 {
		t.Errorf("second bucket name/retention = %q/%d, want deleted-bucket-two/30", second.Name, second.RetentionDays)
	}
	wantInitial := time.Date(2026, 5, 15, 8, 30, 0, 0, time.UTC)
	if !second.InitialCreatedDate.Equal(wantInitial) {
		t.Errorf("second bucket InitialCreatedDate = %v, want %v", second.InitialCreatedDate, wantInitial)
	}
}

func TestListSoftDeletedBuckets_NilInput(t *testing.T) {
	var req *http.Request
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req = r
		_, _ = w.Write([]byte(`<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult><Buckets/></ListAllMyBucketsResult>`))
	}))
	defer server.Close()

	cli, err := New(context.Background(),
		WithEndpoint(server.URL),
		WithAccessKeypair("test-key", "test-secret"),
	)
	if err != nil {
		t.Fatal(err)
	}

	out, err := cli.ListSoftDeletedBuckets(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}

	if got := req.URL.Query().Get("OnlyDeleted"); got != "true" {
		t.Errorf("OnlyDeleted = %q, want true", got)
	}
	if req.URL.Query().Has("continuation-token") {
		t.Error("continuation-token should be omitted when unset")
	}
	if req.URL.Query().Has("max-buckets") {
		t.Error("max-buckets should be omitted when unset")
	}
	if len(out.Buckets) != 0 || out.IsTruncated {
		t.Errorf("output = %+v, want empty untruncated listing", out)
	}
}

func TestListSoftDeletedBuckets_HTTPError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusForbidden)
		_, _ = w.Write([]byte(`<Error><Code>AccessDenied</Code></Error>`))
	}))
	defer server.Close()

	cli, err := New(context.Background(),
		WithEndpoint(server.URL),
		WithAccessKeypair("test-key", "test-secret"),
	)
	if err != nil {
		t.Fatal(err)
	}

	_, err = cli.ListSoftDeletedBuckets(context.Background(), nil)
	if err == nil {
		t.Fatal("expected error for HTTP 403")
	}

	var apiErr smithy.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("error = %v, want smithy.APIError", err)
	}
	if apiErr.ErrorCode() != "AccessDenied" {
		t.Errorf("ErrorCode() = %q, want %q", apiErr.ErrorCode(), "AccessDenied")
	}
}

func TestRestoreSoftDeletedObject_RequestConstruction(t *testing.T) {
	tests := []struct {
		name        string
		key         string
		versionID   string
		wantPath    string
		wantVersion string
	}{
		{"latest", "my-key", "", "/my-bucket/my-key", ""},
		{"specific version", "my-key", "1775929768707198086", "/my-bucket/my-key", "1775929768707198086"},
		{"key with slash and space", "folder/my file.txt", "", "/my-bucket/folder/my file.txt", ""},
		{"key with percent", "100%done.txt", "", "/my-bucket/100%done.txt", ""},
		{"key with reserved chars", "weird?#&.txt", "", "/my-bucket/weird?#&.txt", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var req *http.Request
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				req = r
				w.WriteHeader(http.StatusOK)
			}))
			defer server.Close()

			cli, err := New(context.Background(),
				WithEndpoint(server.URL),
				WithAccessKeypair("test-key", "test-secret"),
			)
			if err != nil {
				t.Fatal(err)
			}

			if _, err := cli.RestoreSoftDeletedObject(context.Background(), &RestoreSoftDeletedObjectInput{
				Bucket:    "my-bucket",
				Key:       tt.key,
				VersionID: tt.versionID,
			}); err != nil {
				t.Fatal(err)
			}

			if req.Method != http.MethodPost {
				t.Errorf("method = %q, want POST", req.Method)
			}
			if req.URL.Path != tt.wantPath {
				t.Errorf("path = %q, want %q", req.URL.Path, tt.wantPath)
			}
			if !req.URL.Query().Has("restore") {
				t.Error("missing ?restore query parameter")
			}
			if got := req.Header.Get("X-Tigris-Restore-Type"); got != "soft-delete" {
				t.Errorf("X-Tigris-Restore-Type = %q, want soft-delete", got)
			}
			if got := req.Header.Get("X-Tigris-Restore-Version"); got != tt.wantVersion {
				t.Errorf("X-Tigris-Restore-Version = %q, want %q", got, tt.wantVersion)
			}
			if req.Header.Get("Authorization") == "" {
				t.Error("missing Authorization header (SigV4)")
			}
		})
	}
}

func TestRestoreSoftDeletedObject_Validation(t *testing.T) {
	cli := &Client{}
	if _, err := cli.RestoreSoftDeletedObject(context.Background(), &RestoreSoftDeletedObjectInput{Key: "key"}); !errors.Is(err, ErrMissingBucket) {
		t.Errorf("err = %v, want ErrMissingBucket", err)
	}
	if _, err := cli.RestoreSoftDeletedObject(context.Background(), &RestoreSoftDeletedObjectInput{Bucket: "bucket"}); !errors.Is(err, ErrMissingKey) {
		t.Errorf("err = %v, want ErrMissingKey", err)
	}
}

func TestPermanentlyDeleteObject_Validation(t *testing.T) {
	cli := &Client{}
	if _, err := cli.PermanentlyDeleteObject(context.Background(), "", "key", "v1"); !errors.Is(err, ErrMissingBucket) {
		t.Errorf("err = %v, want ErrMissingBucket", err)
	}
	if _, err := cli.PermanentlyDeleteObject(context.Background(), "bucket", "", "v1"); !errors.Is(err, ErrMissingKey) {
		t.Errorf("err = %v, want ErrMissingKey", err)
	}
	if _, err := cli.PermanentlyDeleteObject(context.Background(), "bucket", "key", ""); !errors.Is(err, ErrMissingVersionID) {
		t.Errorf("err = %v, want ErrMissingVersionID", err)
	}
}

func TestRestoreBucket_RequestConstruction(t *testing.T) {
	var req *http.Request
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req = r
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	cli, err := New(context.Background(),
		WithEndpoint(server.URL),
		WithAccessKeypair("test-key", "test-secret"),
	)
	if err != nil {
		t.Fatal(err)
	}

	if _, err := cli.RestoreBucket(context.Background(), &RestoreBucketInput{Bucket: "my-bucket"}); err != nil {
		t.Fatal(err)
	}

	if req.Method != http.MethodPost {
		t.Errorf("method = %q, want POST", req.Method)
	}
	if req.URL.Path != "/my-bucket" {
		t.Errorf("path = %q, want /my-bucket", req.URL.Path)
	}
	if !req.URL.Query().Has("restore") {
		t.Error("missing ?restore query parameter")
	}
	if req.Header.Get("Authorization") == "" {
		t.Error("missing Authorization header (SigV4)")
	}
}

func TestSetBucketSoftDelete_RequestConstruction(t *testing.T) {
	tests := []struct {
		name              string
		enabled           bool
		retentionDays     int
		wantEnabled       bool
		wantRetentionDays int // 0 means the field should be omitted
	}{
		{"enable default", true, 0, true, 0},
		{"enable custom", true, 30, true, 30},
		{"disable", false, 30, false, 0},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var req *http.Request
			var body []byte
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				req = r
				body, _ = io.ReadAll(r.Body)
				w.WriteHeader(http.StatusOK)
			}))
			defer server.Close()

			cli, err := New(context.Background(),
				WithEndpoint(server.URL),
				WithAccessKeypair("test-key", "test-secret"),
			)
			if err != nil {
				t.Fatal(err)
			}

			if _, err := cli.SetBucketSoftDelete(context.Background(), &SetBucketSoftDeleteInput{
				Bucket:        "my-bucket",
				Enabled:       tt.enabled,
				RetentionDays: tt.retentionDays,
			}); err != nil {
				t.Fatal(err)
			}

			if req.Method != http.MethodPatch {
				t.Errorf("method = %q, want PATCH", req.Method)
			}
			if req.URL.Path != "/my-bucket" {
				t.Errorf("path = %q, want /my-bucket", req.URL.Path)
			}
			if got := req.Header.Get("Content-Type"); got != "application/json" {
				t.Errorf("content-type = %q, want application/json", got)
			}

			var parsed patchBucketBody
			if err := json.Unmarshal(body, &parsed); err != nil {
				t.Fatalf("failed to unmarshal body %q: %v", body, err)
			}
			if parsed.SoftDelete.Enabled != tt.wantEnabled {
				t.Errorf("enabled = %v, want %v", parsed.SoftDelete.Enabled, tt.wantEnabled)
			}
			if parsed.SoftDelete.RetentionDays != tt.wantRetentionDays {
				t.Errorf("retention_days = %d, want %d", parsed.SoftDelete.RetentionDays, tt.wantRetentionDays)
			}

			// Confirm retention_days is physically absent from the JSON when omitted.
			hasRetention := jsonHasKey(t, body, "retention_days")
			if tt.wantRetentionDays == 0 && hasRetention {
				t.Error("retention_days should be omitted from JSON when 0")
			}
			if tt.wantRetentionDays != 0 && !hasRetention {
				t.Error("retention_days should be present in JSON when set")
			}
		})
	}
}

// A negative window is not the same as an unset one. Zero means "server
// default"; anything else, negative included, goes to the server so an
// out-of-range window is reported instead of silently becoming 7 days.
func TestSoftDelete_NegativeRetentionDaysReachesServer(t *testing.T) {
	t.Run("SetBucketSoftDelete", func(t *testing.T) {
		var body []byte
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			body, _ = io.ReadAll(r.Body)
			w.WriteHeader(http.StatusOK)
		}))
		defer server.Close()

		cli, err := New(context.Background(),
			WithEndpoint(server.URL),
			WithAccessKeypair("test-key", "test-secret"),
		)
		if err != nil {
			t.Fatal(err)
		}

		if _, err := cli.SetBucketSoftDelete(context.Background(), &SetBucketSoftDeleteInput{
			Bucket:        "my-bucket",
			Enabled:       true,
			RetentionDays: -1,
		}); err != nil {
			t.Fatal(err)
		}

		var parsed patchBucketBody
		if err := json.Unmarshal(body, &parsed); err != nil {
			t.Fatalf("unmarshalling body %s: %v", body, err)
		}
		if parsed.SoftDelete.RetentionDays != -1 {
			t.Errorf("retention_days = %d, want -1 forwarded to the server", parsed.SoftDelete.RetentionDays)
		}
	})

	t.Run("CreateBucketWithSoftDelete", func(t *testing.T) {
		var req *http.Request
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			req = r
			w.WriteHeader(http.StatusOK)
		}))
		defer server.Close()

		cli, err := New(context.Background(),
			WithEndpoint(server.URL),
			WithAccessKeypair("test-key", "test-secret"),
			WithPathStyle(true),
		)
		if err != nil {
			t.Fatal(err)
		}

		if _, err := cli.CreateBucketWithSoftDelete(context.Background(), &CreateBucketWithSoftDeleteInput{
			CreateBucketInput: &s3.CreateBucketInput{Bucket: aws.String("my-bucket")},
			RetentionDays:     -1,
		}); err != nil {
			t.Fatal(err)
		}

		if got := req.Header.Get("X-Tigris-Soft-Delete"); got != "-1" {
			t.Errorf("X-Tigris-Soft-Delete = %q, want -1 forwarded to the server", got)
		}
	})
}

func TestSetBucketSoftDelete_Validation(t *testing.T) {
	cli := &Client{}
	if _, err := cli.SetBucketSoftDelete(context.Background(), &SetBucketSoftDeleteInput{Enabled: true}); !errors.Is(err, ErrMissingBucket) {
		t.Errorf("err = %v, want ErrMissingBucket", err)
	}
}

func TestForceDeleteBucket_Validation(t *testing.T) {
	cli := &Client{}
	tests := []struct {
		name string
		in   *s3.DeleteBucketInput
	}{
		{"nil input", nil},
		{"nil bucket", &s3.DeleteBucketInput{}},
		{"empty bucket", &s3.DeleteBucketInput{Bucket: aws.String("")}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// A nil input must not reach the AWS SDK, where it panics. This is the
			// most destructive method in the file, so it fails closed like its
			// siblings.
			if _, err := cli.ForceDeleteBucket(context.Background(), tt.in); !errors.Is(err, ErrMissingBucket) {
				t.Errorf("err = %v, want ErrMissingBucket", err)
			}
		})
	}
}

func TestForceDeleteBucket_RequestConstruction(t *testing.T) {
	var req *http.Request
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req = r
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	cli, err := New(context.Background(),
		WithEndpoint(server.URL),
		WithAccessKeypair("test-key", "test-secret"),
		WithPathStyle(true),
	)
	if err != nil {
		t.Fatal(err)
	}

	if _, err := cli.ForceDeleteBucket(context.Background(), &s3.DeleteBucketInput{
		Bucket: aws.String("my-bucket"),
	}); err != nil {
		t.Fatal(err)
	}

	if req.Method != http.MethodDelete {
		t.Errorf("method = %q, want DELETE", req.Method)
	}
	if got := req.Header.Get("X-Tigris-Force-Delete"); got != "true" {
		t.Errorf("X-Tigris-Force-Delete = %q, want true", got)
	}
}

func TestPermanentlyDeleteObject_RequestConstruction(t *testing.T) {
	var req *http.Request
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req = r
		w.WriteHeader(http.StatusNoContent)
	}))
	defer server.Close()

	cli, err := New(context.Background(),
		WithEndpoint(server.URL),
		WithAccessKeypair("test-key", "test-secret"),
		WithPathStyle(true),
	)
	if err != nil {
		t.Fatal(err)
	}

	if _, err := cli.PermanentlyDeleteObject(context.Background(), "my-bucket", "my-key", "1775929768707198086"); err != nil {
		t.Fatal(err)
	}

	if req.Method != http.MethodDelete {
		t.Errorf("method = %q, want DELETE", req.Method)
	}
	if req.URL.Path != "/my-bucket/my-key" {
		t.Errorf("path = %q, want /my-bucket/my-key", req.URL.Path)
	}
	if got := req.URL.Query().Get("versionId"); got != "1775929768707198086" {
		t.Errorf("versionId = %q, want 1775929768707198086", got)
	}
	if got := req.Header.Get("X-Tigris-Soft-Delete"); got != "true" {
		t.Errorf("X-Tigris-Soft-Delete = %q, want true", got)
	}
}

func TestCreateBucketWithSoftDelete_RequestConstruction(t *testing.T) {
	tests := []struct {
		name          string
		retentionDays int
		wantHeader    string
	}{
		{"default window", 0, "true"},
		{"custom window", 30, "30"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var req *http.Request
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				req = r
				w.WriteHeader(http.StatusOK)
			}))
			defer server.Close()

			cli, err := New(context.Background(),
				WithEndpoint(server.URL),
				WithAccessKeypair("test-key", "test-secret"),
				WithPathStyle(true),
			)
			if err != nil {
				t.Fatal(err)
			}

			if _, err := cli.CreateBucketWithSoftDelete(context.Background(), &CreateBucketWithSoftDeleteInput{
				CreateBucketInput: &s3.CreateBucketInput{
					Bucket: aws.String("my-bucket"),
				},
				RetentionDays: tt.retentionDays,
			}); err != nil {
				t.Fatal(err)
			}

			if req.Method != http.MethodPut {
				t.Errorf("method = %q, want PUT", req.Method)
			}
			if got := req.Header.Get("X-Tigris-Soft-Delete"); got != tt.wantHeader {
				t.Errorf("X-Tigris-Soft-Delete = %q, want %q", got, tt.wantHeader)
			}
		})
	}
}

func TestRestoreBucket_HTTPError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotFound)
		_, _ = w.Write([]byte(`<Error><Code>NoSuchBucket</Code></Error>`))
	}))
	defer server.Close()

	cli, err := New(context.Background(),
		WithEndpoint(server.URL),
		WithAccessKeypair("test-key", "test-secret"),
	)
	if err != nil {
		t.Fatal(err)
	}

	_, err = cli.RestoreBucket(context.Background(), &RestoreBucketInput{Bucket: "my-bucket"})
	if err == nil {
		t.Fatal("expected error for HTTP 404")
	}

	var apiErr *APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("error = %v, want *APIError", err)
	}
	if apiErr.Op != "RestoreBucket" {
		t.Errorf("Op = %q, want %q", apiErr.Op, "RestoreBucket")
	}
	if apiErr.StatusCode != http.StatusNotFound {
		t.Errorf("StatusCode = %d, want %d", apiErr.StatusCode, http.StatusNotFound)
	}
	if apiErr.Code != "NoSuchBucket" {
		t.Errorf("Code = %q, want %q", apiErr.Code, "NoSuchBucket")
	}
}

func jsonHasKey(t *testing.T, body []byte, key string) bool {
	t.Helper()
	var generic map[string]json.RawMessage
	if err := json.Unmarshal(body, &generic); err != nil {
		t.Fatalf("failed to unmarshal body: %v", err)
	}
	sd, ok := generic["soft_delete"]
	if !ok {
		t.Fatal("body missing soft_delete object")
	}
	var inner map[string]json.RawMessage
	if err := json.Unmarshal(sd, &inner); err != nil {
		t.Fatalf("failed to unmarshal soft_delete: %v", err)
	}
	_, present := inner[key]
	return present
}

// skipIfNoCreds skips integration tests when Tigris credentials are absent.
func skipIfNoCreds(t *testing.T) {
	t.Helper()
	if os.Getenv("TIGRIS_STORAGE_ACCESS_KEY_ID") == "" ||
		os.Getenv("TIGRIS_STORAGE_SECRET_ACCESS_KEY") == "" {
		t.Skip("skipping: TIGRIS_STORAGE_ACCESS_KEY_ID and TIGRIS_STORAGE_SECRET_ACCESS_KEY not set")
	}
}

// TestSoftDeleteLifecycle_integration exercises the full soft-delete lifecycle
// against a live Tigris endpoint when credentials are available.
func TestSoftDeleteLifecycle_integration(t *testing.T) {
	skipIfNoCreds(t)

	ctx := context.Background()
	cli, err := New(ctx)
	if err != nil {
		t.Fatal(err)
	}

	bucket := "storage-go-softdelete-test-" + strconv.FormatInt(time.Now().UnixNano(), 36)

	if _, err := cli.CreateBucketWithSoftDelete(ctx, &CreateBucketWithSoftDeleteInput{
		CreateBucketInput: &s3.CreateBucketInput{
			Bucket: aws.String(bucket),
		},
		RetentionDays: 7,
	}); err != nil {
		t.Fatalf("CreateBucketWithSoftDelete: %v", err)
	}
	t.Cleanup(func() {
		_, _ = cli.ForceDeleteBucket(ctx, &s3.DeleteBucketInput{Bucket: aws.String(bucket)})
	})

	key := "hello.txt"
	if _, err := cli.PutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
		Body:   strings.NewReader("hello world"),
	}); err != nil {
		t.Fatalf("PutObject: %v", err)
	}

	if _, err := cli.DeleteObject(ctx, &s3.DeleteObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	}); err != nil {
		t.Fatalf("DeleteObject: %v", err)
	}

	listed, err := cli.ListSoftDeletedObjects(ctx, &ListSoftDeletedObjectsInput{Bucket: bucket})
	if err != nil {
		t.Fatalf("ListSoftDeletedObjects: %v", err)
	}
	var found bool
	for _, o := range listed.Objects {
		if o.Key == key && o.SoftDeleted {
			found = true
		}
	}
	if !found {
		t.Errorf("soft-deleted object %q not found in listing: %+v", key, listed.Objects)
	}

	if _, err := cli.RestoreSoftDeletedObject(ctx, &RestoreSoftDeletedObjectInput{
		Bucket: bucket,
		Key:    key,
	}); err != nil {
		t.Fatalf("RestoreSoftDeletedObject: %v", err)
	}

	if _, err := cli.ForceDeleteBucket(ctx, &s3.DeleteBucketInput{Bucket: aws.String(bucket)}); err != nil {
		t.Fatalf("ForceDeleteBucket: %v", err)
	}

	// Soft-delete state is eventually consistent, so poll the deleted-buckets
	// listing (paginating, as other soft-deleted buckets may be present) until
	// the bucket shows up or the deadline passes.
	deadline := time.Now().Add(15 * time.Second)
	for {
		if findSoftDeletedBucket(ctx, t, cli, bucket) {
			break
		}
		if time.Now().After(deadline) {
			t.Fatalf("soft-deleted bucket %q not found in ListSoftDeletedBuckets", bucket)
		}
		time.Sleep(time.Second)
	}
}

// findSoftDeletedBucket reports whether the named bucket appears in the
// soft-deleted buckets listing, following pagination.
func findSoftDeletedBucket(ctx context.Context, t *testing.T, cli *Client, bucket string) bool {
	t.Helper()

	var token string
	for {
		listed, err := cli.ListSoftDeletedBuckets(ctx, &ListSoftDeletedBucketsInput{ContinuationToken: token})
		if err != nil {
			t.Fatalf("ListSoftDeletedBuckets: %v", err)
		}
		for _, b := range listed.Buckets {
			if b.Name == bucket {
				return true
			}
		}
		if !listed.IsTruncated {
			return false
		}
		token = listed.NextContinuationToken
	}
}

// TestSigV4CanonicalPath_NotDoubleEscaped pins the signing rule that Tigris
// applies: the canonical URI is the request path encoded exactly once.
//
// The request path is already percent-encoded when it reaches the signer, so the
// signer must run with DisableURIPathEscaping. Without it the canonical URI is
// encoded a second time and every key holding a space, "%", "+", "#", "?", or a
// non-ASCII byte fails with SignatureDoesNotMatch. Plain ASCII keys are
// unaffected, which is why this needs its own test.
//
// The check re-signs the received request both ways and asserts the client
// matched the single-encoded form. Verifying the reconstruction reproduces the
// client's own Authorization header is what makes the comparison meaningful.
func TestSigV4CanonicalPath_NotDoubleEscaped(t *testing.T) {
	keys := []string{
		"my-key",
		"folder/my file.txt",
		"100%done.txt",
		"café.txt",
		"a+b=c",
		"weird?#&.txt",
	}

	for _, key := range keys {
		t.Run(key, func(t *testing.T) {
			var gotAuth, wantSingle, wantDouble string

			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				gotAuth = r.Header.Get("Authorization")

				signingTime, err := time.Parse("20060102T150405Z", r.Header.Get("X-Amz-Date"))
				if err != nil {
					t.Errorf("parsing X-Amz-Date: %v", err)
					return
				}

				resign := func(disableEscaping bool) string {
					rebuilt, err := http.NewRequest(r.Method, "http://"+r.Host+r.RequestURI, nil)
					if err != nil {
						t.Errorf("rebuilding request: %v", err)
						return ""
					}
					for _, name := range signedHeaderNames(gotAuth) {
						if name == "host" {
							continue
						}
						rebuilt.Header.Set(name, r.Header.Get(name))
					}

					signer := v4.NewSigner(func(o *v4.SignerOptions) {
						o.DisableURIPathEscaping = disableEscaping
					})
					err = signer.SignHTTP(context.Background(),
						aws.Credentials{AccessKeyID: "test-key", SecretAccessKey: "test-secret"},
						rebuilt, r.Header.Get("X-Amz-Content-Sha256"), "s3", "auto", signingTime)
					if err != nil {
						t.Errorf("re-signing: %v", err)
						return ""
					}
					return rebuilt.Header.Get("Authorization")
				}

				wantSingle = resign(true)
				wantDouble = resign(false)
				w.WriteHeader(http.StatusOK)
			}))
			defer server.Close()

			cli, err := New(context.Background(),
				WithEndpoint(server.URL),
				WithAccessKeypair("test-key", "test-secret"),
				WithRegion("auto"),
			)
			if err != nil {
				t.Fatal(err)
			}

			if _, err := cli.RestoreSoftDeletedObject(context.Background(), &RestoreSoftDeletedObjectInput{
				Bucket: "my-bucket",
				Key:    key,
			}); err != nil {
				t.Fatal(err)
			}

			if gotAuth != wantSingle {
				t.Errorf("signature was not computed over the single-encoded path\n got: %s\nwant: %s", gotAuth, wantSingle)
			}
			// Guards the test itself: for a key that the double-escaping bug would
			// corrupt, the two forms must differ, or this test proves nothing.
			if key != "my-key" && wantSingle == wantDouble {
				t.Errorf("key %q does not distinguish single from double escaping; pick another", key)
			}
		})
	}
}

// signedHeaderNames pulls the SignedHeaders list out of a SigV4 Authorization
// header value.
func signedHeaderNames(auth string) []string {
	const marker = "SignedHeaders="
	i := strings.Index(auth, marker)
	if i < 0 {
		return nil
	}
	rest := auth[i+len(marker):]
	if j := strings.Index(rest, ","); j >= 0 {
		rest = rest[:j]
	}
	return strings.Split(rest, ";")
}

// countingHTTPClient records how many requests it sends, so a test can prove the
// raw-HTTP path used it instead of the package-level client.
type countingHTTPClient struct {
	inner *http.Client
	calls int
}

func (c *countingHTTPClient) Do(req *http.Request) (*http.Response, error) {
	c.calls++
	return c.inner.Do(req)
}

// The raw-HTTP methods must send through the HTTPClient configured on the
// underlying S3 client. Discarding it would drop any custom transport, TLS
// config, proxy, or tracing hook the caller installed.
func TestDoSignedRequest_UsesConfiguredHTTPClient(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_, _ = w.Write([]byte(sampleListBucketsXML))
	}))
	defer server.Close()

	counter := &countingHTTPClient{inner: server.Client()}

	cli := &Client{Client: s3.New(s3.Options{
		BaseEndpoint: aws.String(server.URL),
		Region:       "auto",
		Credentials:  credentials.NewStaticCredentialsProvider("test-key", "test-secret", ""),
		HTTPClient:   counter,
	})}

	if _, err := cli.ListSoftDeletedBuckets(context.Background(), nil); err != nil {
		t.Fatal(err)
	}

	if counter.calls != 1 {
		t.Errorf("configured HTTP client saw %d requests, want 1", counter.calls)
	}
}
